# Generated by Django 3.1.6 on 2021-11-12 15:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RatingGiven', models.IntegerField(default=0)),
                ('NewsCompany', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(default=0)),
                ('newsHeadline', models.CharField(default='', max_length=60)),
                ('newsCategory', models.CharField(default='', max_length=20)),
                ('news', ckeditor.fields.RichTextField(default='', max_length=15000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='News.reporter')),
            ],
        ),
    ]
