# Generated by Django 3.1.6 on 2021-10-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20211028_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItemRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('comment', models.CharField(default='', max_length=500)),
                ('bookingItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
