# Generated by Django 3.1.6 on 2021-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingitemrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='image',
            field=models.ImageField(default='', upload_to='booking/images'),
        ),
    ]
