# Generated by Django 3.1.6 on 2021-11-14 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_ordernotification'),
        ('booking', '0006_bookingnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingNotification',
            new_name='AppointmentNotification',
        ),
    ]
