# Generated by Django 3.1.6 on 2021-09-17 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subCategory', models.CharField(default='', max_length=50)),
                ('originalPrice', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('rating', models.FloatField(default=0.0)),
                ('ratingNo', models.IntegerField(default=0)),
                ('inStock', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
    ]
