# Generated by Django 3.1.6 on 2021-09-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_order_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='PinCode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='RatingGiven',
            new_name='ratingGiven',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='PinCode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='RatingNo',
            new_name='ratingNo',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='ShopAddress',
            new_name='shopAddress',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='ShopCategory',
            new_name='shopCategory',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='ShopImg',
            new_name='shopImg',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='ShopName',
            new_name='shopName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNo',
            new_name='PhoneNo',
        ),
    ]
