# Generated by Django 3.1.6 on 2021-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210917_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='appointmentBased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='productBased',
            field=models.BooleanField(default=True),
        ),
    ]
