# Generated by Django 3.1.6 on 2021-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
